trigger:
- main

pool: test

jobs:
- job: Job
  steps:
  - task: Maven@3
    displayName: 'Initialize Job'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'
  
  - task: Maven@3
    displayName: 'Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'compile'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'
  
  - task: Maven@3
    displayName: 'Finalize Job'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install -DskipTests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'